* uchronia.el - Rewrite the minibuffer history

#+html: <a href="https://www.gnu.org/software/emacs/"><img alt="GNU Emacs" src="https://github.com/minad/corfu/blob/screenshots/emacs.svg?raw=true"/></a>

*NOTE*: This package has been superseded by the ~vertico-repeat~ extension of my
[[https://github.com/minad/vertico][Vertico]] completion UI. The ~vertico-repeat~ command is Vertico-specific, but more
powerful since it also stores the currently selected candidate. Therefore I
recommend ~vertico-repeat~ over Uchronia.

This small unreleased package provides the ~uchronia-mode~ which stores the
history for every minibuffer and completion command. The last recent minibuffer
session can then be restarted using ~uchronia-repeat~. Furthermore one can
select from the list of recent minibuffer sessions using ~uchronia-select~.

Both ~uchronia-repeat~ and ~uchronia-select~ allow to restart the minibuffer
session and edit the historical input, they allow rewriting the history.
Therefore the name [[https://en.wikipedia.org/wiki/Alternate_history][Uchronia]].
